list1=(input("Enter the first list: ")).split()
list2=(input("Enter the second list: ")).split()

set1=set (map(int,list1))
set2=set(map(int,list2))
print("first set",set1)
print("second set",set2)
print("union:",set1.union(set2))
print("intersection:",set1.intersection(set2))
print("difference:",set1.difference(set2))
print("symmetric difference:",set1.symmetric_difference(set2))